# put your secret values and credentials here. do not share this file and do not push it to github
[sources.google_analytics.credentials]
type = "service_account"
project_id = "project_id" # Add project_id
private_key_id = "project_key_id" # Add project_key_id
private_key = "private_key" # Add private_key
client_email = "client_email" # Add client_email
client_id = "client_id" # Add client_id
auth_uri = "auth_uri" # Add auth_uri
token_uri = "token_uri" # Add token_uri
auth_provider_x509_cert_url = "auth_provider_x509_cert_url" # Add auth_provider_x509_cert_url
client_x509_cert_url = "client_x509_cert_url" # Add client_x509_cert_url
